import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./stores";
import { registerGlobalComponents } from "@/utils/import";
import BaseButton from "@/components/bases/BaseButton.vue";
import BaseTextfield from "@/components/bases/BaseTextfield.vue";
import BaseDropdown from "@/components/bases/BaseDropdown.vue";
import BaseCombobox from "@/components/bases/BaseCombobox.vue";
import BaseLoading from "@/components/bases/BaseLoading.vue";
import BaseToastMessage from "@/components/bases/BaseToastMessage.vue";
import BaseDialog from "@/components/bases/BaseDialog.vue";
import BasePaging from "@/components/bases/BasePaging.vue";
import AutoFocus from "@/components/directives/AutoFocus";
import "@/utils/globalExtensions";
const app = createApp(App);
app.component("BButton", BaseButton);
app.component("BTextfield", BaseTextfield);
app.component("BDropdown", BaseDropdown);
app.component("BCombobox", BaseCombobox);
app.component("BLoading", BaseLoading);
app.component("BToastMessage", BaseToastMessage);
app.component("BDialog", BaseDialog);
app.component("BPaging", BasePaging);
app.directive("auto-focus", AutoFocus);
registerGlobalComponents(app);
app.use(router);
app.use(store);
app.mount("#app");
